### PR TITLE
Stage 1 markup jsx api

### PR DESCRIPTION
**Pull request by flysputnik17**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello! You did a good job with your first diploma stage! Some fixing will be required, please find list of issues below. I hope tehy will be easy to fix! Good luck!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

*  https://snipboard.io/W5Vtbz.jpg Active link in the menu should be underlined, please check figma

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://snipboard.io/a1eGl0.jpg Content should be centered on intermediate resolutions. Also note that gap between logo and Home link is too small, would be better to increase the breakpoint for sandwich menu.
* https://snipboard.io/OZXbQ3.jpg Should be the same background color as search results
* tablet and desktop resolutions should have three cards in a row

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should be working links, opening in new tabs

- [x]  Classes are named according to BEM specifications.

* https://snipboard.io/yhxIcs.jpg Menu buttons need the same class, they have the same styles and serve the same purpose. For the active link, you can add a modifier.
* https://snipboard.io/Tb9yhs.jpg Not the best class name, this it a logout button, elise is just a sample user name from figma


- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Search form should be a `<form>`
* Links in `header` and `footer` should be in nav, ul or ul inside nav.
* Home page is missing h1
* `about__text-paragraph` - please don't use br inside a paragraph. The text in `about` contains two paragraphs, semantically, you need to remove br and use two `<p>`
* heading in modal can't be h1, it's not the main heading of the page.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Search button is missing hover and active states

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

Please, use raster graphics format for photos in a gallery, backgrounds and other content pictures (jpg or png). Vector graphics is necessary for icons and logos, pictures (often with transparent background) which need to be flexible and scalable. For content pictures of the page, where we need a vast color shading and depth variation, it's a good practice to use raster graphics.

https://designshack.net/articles/layouts/vector-vs-raster-what-do-i-use/

## Number of points: 48

**Comment by flysputnik17** [comment]
hii i fixed the issues you listed

**Comment by ImaliaNsk** [comment]
Thanks for the fixes, they looks great! Only a few points short of a goal. Please find the issues in the list below and make necessary fixes. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Necessary to truncate long text in cards: https://snipboard.io/fQkxYt.jpg

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* https://snipboard.io/ydYBwU.jpg Should be the same background color as search results
* tablet and desktop resolutions should have three cards in a row

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

Please, use raster graphics format for photos in a gallery, backgrounds and other content pictures (jpg or png). Vector graphics is necessary for icons and logos, pictures (often with transparent background) which need to be flexible and scalable. For content pictures of the page, where we need a vast color shading and depth variation, it's a good practice to use raster graphics.

https://designshack.net/articles/layouts/vector-vs-raster-what-do-i-use/

## Number of points: 73

**Comment by flysputnik17** [comment]
hello i fixed the horizontal scrolling on resolutions of 320px and  background color , long text in cards hope its 👌

**Comment by ImaliaNsk** [comment]
Almost there, but a few issues still remain, text in the cards is now just cropped, and the cards layout needs small fixing.
 
# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Necessary to truncate long text in cards: https://snipboard.io/s105Ma.jpg, now it's just cropped

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* tablet and desktop resolutions should have three cards in a row, all cards should be the same width, and centered https://snipboard.io/WGNKLa.jpg

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 75

**Comment by flysputnik17** [comment]
hi i made the fixes

**Comment by ImaliaNsk** [comment]
Congratulations, the project looks perfect! I wish you success in your future projects!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
